### ISSUE TITLE
sub-sub-commands

### ISSUE THREAD

**Issue by eins78** [basecamp/sub#22]
How hard would it be to support sub-sub commands with the same autocompletion and help generation via in-line comments?

I am thinking of something like sub-folders

```
├── bin                   # contains the main executable for your program
├── libexec               # where the subcommand executables are
   ├── sub-command        # a sub-folder, containing 'sub-command-subcommand' scripts
```

An example where this would be useful is a `script` subcommand: One could stash away specialized stuff that should not clutter the `commands` output.
It would also allow a simple hierarchy without glueing together the script manually.

In the [blog post](http://37signals.com/svn/posts/3264-automating-with-convention-introducing-sub) you have the line `37 script basecamp file_usage_summary`. 
Is this the same kind of thinking or just is it just one subcommand which does more or less the same thing with different arguments which happens to be called `script`?

**Comment by malvim** [comment]
This looks interesting.

Any news on this? Is this working at all? Should I clone @jeffreyroberts ' repo insted of basecamp's? :)

**Comment by jeremy** [comment]
#37
