### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by ljrpicasso** [basecamp/sub#26]
I've put together a sub-new command for generating the template for a new sub command. It is written in ruby, because I wanted to make use of the ERB handling - the alternate language generators are just ERB templates. I've got simple examples for bash and ruby. There are no dependencies on outside gems, because our concept was to limit this type of dependency.

Not sure if a pull request is appropriate, since this would add a dependency for ruby, but for the people I know, this isn't a problem. 

Any ideas? Should I pass it up?

John

**Comment by jeremy** [comment]
#38
