### ISSUE TITLE
mysub:10: command not found: my sub

### ISSUE THREAD

**Issue by cmalven** [basecamp/sub#28]
My sub is called `cmal` and is installed at `~/Dropbox/Dropbox/Config/sub/cmal`

My .zshenv contains: 

```
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
eval "$($HOME/Dropbox/Config/sub/cmal/bin/cmal init -)"
```

Whenever I open a new terminal, and run `cmal` I get `cmal:10: command not found: cmal`

If I then run `source ~/.zshenv` followed by `cmal` I correctly get the usage.

But every time I open a new terminal window I'm back to square one. Any idea what could be going on?

**Comment by jeremy** [comment]
Looks like #32
