### ISSUE TITLE
Issue with "kiva init -"

### ISSUE THREAD

**Issue by Nattle** [basecamp/sub#39]
I still get this (again) when i setup the script:
-bash: eval: line 12: syntax error near unexpected token `)'
-bash: eval: line 12:`  )'

I've tracked it down to  "kiva commands --sh" not returning anything. I should be spitting out "shell". 

I can fix it by replacing   ${commands[*]}) with shell)

**Comment by gerhard** [comment]
Have you deleted `libexec/kiva-sh-shell`?
