### ISSUE TITLE
Maybe list notable forks?

### ISSUE THREAD

**Issue by bf4** [basecamp/sub#44]
- https://github.com/jdevera/sub
- https://github.com/jeffreyroberts/sub
- https://github.com/zillow/sub
- https://github.com/subvisual/tool
- https://github.com/depeele/sub/tree/sub-commands
- https://github.com/raffomania/sub
- https://github.com/toumorokoshi/sub
- https://github.com/Everapps/ev
- https://github.com/hutufairy/sub
- https://github.com/evnm/sub/tree/exec-instead-of-bin-symlink
- https://github.com/michaeltruong/tv/tree/develop
- https://github.com/mislav/sub/tree/init-wrapper
- https://github.com/vincentbernat/sub/tree/fix/zsh-completion

**Comment by FluxBotnet** [comment]
+1

**Comment by markstos** [comment]
A current list of forks is already easily found through Github. To separate "notable" forks from non-notable forks, some notes are ended. That is: the unique features of each of the notable forks should be noted.  

There are a enough forks that this list might remain in a state of flux, so a wiki page that several people could tribute too would be better than putting out new releases just to update the README with new notes about the latest fork status.

**Comment by keithy** [comment]
Simpler and older: https://github.com/keithy/groan

**Comment by cornfeedhobo** [comment]
@markstos I always reads these types of issues as subtle messages to the repo owner to address the stale issues and pull requests. I think this repo not having a merge since 2012 is reason enough to bring this up.
